### ISSUE TITLE
Mobile responsive layout based on sidebar expanding

### ISSUE THREAD

**Issue by ribab** [mckinsey/vizro#1096]
### Which package?

vizro

### What's the problem this feature will solve?

When sizing the page to be very narrow, some layouts just don't look good (like mobile layout)

and it especially doesn't look good when expanding the side-bar.

I noticed there is already some kind of mobile layout but it doesn't respond to the sidebar expanding. I'm not sure how that currently works so the below proposed solution could be different based on how the mobile layout currently works.

### Describe the solution you'd like

Add something like this to the CSS so the layout responds to whether the side-bar is opened:

```css
/* Media query for narrow view */
@media screen and (max-width: 768px) {
  #page-main:has(#collapsable-left-side:not(.show)) #page-components {
    display: flex !important;
    flex-direction: column !important;
  }
}

/* Media query for when the sidebar is expanded */
@media screen and (max-width: 1028px) {
  #page-main:has(#collapsable-left-side.show) #page-components {
    display: flex !important;
    flex-direction: column !important;
  }
}
```

### Code of Conduct

- [x] I agree to follow the  [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).
