### ISSUE TITLE
Apply code formatting to code examples in our docs

### ISSUE THREAD

**Issue by antonymilne** [mckinsey/vizro#719]
Currently our code examples are not formatted using `black` or linted in any way.
* Investigate what mkdocs extensions there are to do this and what they would do (e.g. they might run `ruff` or `black`)
* Find a good solution and apply it!

**Comment by Dljdd** [comment]
Hi I can help with this

**Comment by stichbury** [comment]
We could use [`blacken-docs`](https://github.com/adamchainz/blacken-docs) but there's a problem (when isn't there?) which is that we don't surround our code with a standard lexer block anymore because we're using the MkDocs plugin for PyCafe. It may be possible to fork it and build our own version to check blocks for ```{.python pycafe-link}``` ??

Something I'm going to need some advice from @antonymilne or @maxschulz-COL on I think.

**Comment by maxschulz-COL** [comment]
I have already reported on that and there is a ticket and even a PR that aims to finish it. I didn't get around to doing it though.

See https://github.com/adamchainz/blacken-docs/issues/357 for reference

**Comment by stichbury** [comment]
> I'd suggest:
> - @stichbury, given you're the owner of most of our markdown files, see what you think of the changes made by the above pre-commit config involving `mdformat` outside of code snippets

This is great, yes, I can do that. Will you make a branch for that pre-commit, or shall I? Happy to put this into the upcoming sprint to get it further advanced.

**Comment by antonymilne** [comment]
You go for it 🙂 I suggest you start with this:
```
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.18
  hooks:
    - id: mdformat
      args: [--ignore-missing-references, --wrap=no, --align-semantic-breaks-in-lists]
```

and play around with the `args` to see if you like them or if there's any others that you like.

And then afterwards add in this to see what difference it makes:
```
      additional_dependencies:
        - "mdformat-mkdocs[recommended]==3.0.0"
```

**Comment by stichbury** [comment]
I've given it a try here: https://github.com/mckinsey/vizro/tree/docs/update-precommit but two of the args you included (`--ignore-missing-references` and `--align-semantic-breaks-in-lists`) are returning errors for me. They don't seem to be documented in the `mdformat` docs? I'm happy with the word wrap changes so this would work fine for me if the code formatting is OK for you.

**Comment by antonymilne** [comment]
Ah yes, I think those arguments are only added when `"mdformat-mkdocs[recommended]==3.0.0"` is added.

The changes are pretty far-reaching (one reason I didn't do this before as a quick PR) and I think will need some careful checking through, mainly to make sure that the built docs still look ok. e.g. I'm pretty sure that changes like 
`\[`Container`\]\[vizro.models.Container\]` (see https://github.com/KyleKing/mdformat-mkdocs/issues/19) and [this](https://github.com/mckinsey/vizro/compare/main...docs/update-precommit#diff-faeba21fae90fa4f2206f209202eaaa5cd52667bf9cdb785fd851420a627afdc) will have broken things.

What happens if you just run it with this without the `mdformat-mkdocs` at all?
```
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.18
  hooks:
    - id: mdformat
      args: [--wrap=no]
```

(and playing around with any other settings you might like there)

**Comment by stichbury** [comment]
Thanks!

My branch has the [change](https://github.com/mckinsey/vizro/compare/main...docs/update-precommit) for just the `mdformat` initiated wrap changes. There isn't anything else to set for `mdformat` since the only other parameter is for the end of file, which is covered by another lint tool. 

I'll have another play with the mkdocs plugin since I couldn't get it working yesterday but maybe there's an extra space or something in my file.

**Comment by antonymilne** [comment]
Isn't that the change caused by the following configuration though, which includes `mdformat-mkdocs`? This is what the pre-commit.yaml file looks like in the diff you link to:
```
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.18
    hooks:
      - id: mdformat
        args: [--wrap=no]
    additional_dependencies:
      - "mdformat-mkdocs[recommended]==3.0.0"   
```
